# Generated by Django 3.1.7 on 2023-12-15 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('idTarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('compania', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=16, unique=True)),
                ('cvv', models.CharField(max_length=3)),
                ('fechaVencimiento', models.CharField(max_length=5)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.usuario')),
            ],
        ),
    ]
