# Generated by Django 3.1.7 on 2023-12-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tarjeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('idMovimiento', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=20)),
                ('concepto', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tarjetaDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetaDestino', to='Tarjeta.tarjeta')),
                ('tarjetaOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetaOrigen', to='Tarjeta.tarjeta')),
            ],
        ),
    ]
